POST http://localhost:3001/api/persons
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtzczU5ODIiLCJpZCI6IjY2MzQ4NDA2NzI1Y2Y1NjYyNmRlNDA3MSIsImlhdCI6MTcxNDgwMDkwNCwiZXhwIjoxNzE0ODA0NTA0fQ._hJslRLp_HQQtevcn0Wr5T8rLDhMMqYlbwtkRtYw3Rw

{
"name": "Token",
"number": "00-0000000",
"user": "663487b2725cf56626de4075"
}